<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>admin</StaticWebAssetBasePath>
    <StaticWebAssetFingerprintingEnabled>false</StaticWebAssetFingerprintingEnabled>
    <OverrideHtmlAssetPlaceholders>false</OverrideHtmlAssetPlaceholders>
    <PublishAot>false</PublishAot>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <ProjectReference Include="..\SwLicenseWatcher.Core\SwLicenseWatcher.Core.csproj" AdditionalProperties="PublishAot=false;PublishTrimmed=false" />
  </ItemGroup>

</Project>
