version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "12:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 10
    target-branch: main
    labels:
      - dependencies
      - nuget
    groups:
      nuget-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: all

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: UTC
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions-dependencies:
        patterns:
          - "actions/*"
