<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Bcl.Cryptography" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageVersion Include="Microsoft.Data.SqlClient.SNI.runtime" Version="6.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.IdentityModel.Abstractions" Version="8.22.0" />
    <PackageVersion Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.22.0" />
    <PackageVersion Include="Microsoft.IdentityModel.Logging" Version="8.22.0" />
    <PackageVersion Include="Microsoft.IdentityModel.Protocols" Version="8.22.0" />
    <PackageVersion Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.22.0" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="10.0.11" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
    <PackageVersion Include="System.Security.Cryptography.Pkcs" Version="10.0.11" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="10.0.11" />
    <PackageVersion Include="System.ServiceProcess.ServiceController" Version="10.0.11" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.0" />
  </ItemGroup>
</Project>
