using System.Text.Json.Serialization;
using SwLicenseWatcher.Core;

namespace SwLicenseWatcher.Api;

[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(DesignResponse))]
[JsonSerializable(typeof(SchemaStatusResponse))]
[JsonSerializable(typeof(SchemaApplyResponse))]
[JsonSerializable(typeof(UpdateManifest))]
[JsonSerializable(typeof(SnapshotAcceptedResponse))]
[JsonSerializable(typeof(AgentHeartbeatAcceptedResponse))]
[JsonSerializable(typeof(DeviceProfileWriteRequest))]
[JsonSerializable(typeof(DeviceSummary))]
[JsonSerializable(typeof(DeviceListResponse))]
[JsonSerializable(typeof(DeviceDetail))]
[JsonSerializable(typeof(SoftwareAggregate))]
[JsonSerializable(typeof(SoftwareAggregateListResponse))]
[JsonSerializable(typeof(SoftwareDevice))]
[JsonSerializable(typeof(SoftwareDeviceListResponse))]
[JsonSerializable(typeof(PolicyListResponse))]
[JsonSerializable(typeof(ViolationListResponse))]
[JsonSerializable(typeof(AgentUninstallCommand))]
[JsonSerializable(typeof(UninstallRequestCreateRequest))]
[JsonSerializable(typeof(UninstallRequestCreatedResponse))]
[JsonSerializable(typeof(AgentUninstallRequestResponse))]
[JsonSerializable(typeof(UninstallRequestConsumeRequest))]
[JsonSerializable(typeof(AdminUninstallRequest))]
[JsonSerializable(typeof(UninstallRequestListResponse))]
[JsonSerializable(typeof(DeviceUpgradeAuthorizationRequest))]
[JsonSerializable(typeof(DeviceUpgradeAuthorizationResponse))]
[JsonSerializable(typeof(IReadOnlyList<AdminUninstallRequest>))]
[JsonSerializable(typeof(InstalledSoftwareEntry))]
[JsonSerializable(typeof(SoftwarePolicyEntry))]
[JsonSerializable(typeof(SoftwarePolicyWriteRequest))]
[JsonSerializable(typeof(SoftwareClassificationWriteRequest))]
[JsonSerializable(typeof(SoftwareClassificationItemWriteRequest))]
[JsonSerializable(typeof(SoftwareClassificationBatchWriteRequest))]
[JsonSerializable(typeof(SoftwareClassificationBatchResponse))]
[JsonSerializable(typeof(IReadOnlyList<SoftwareClassificationItemWriteRequest>))]
[JsonSerializable(typeof(List<SoftwareClassificationItemWriteRequest>))]
[JsonSerializable(typeof(DeviceSoftwareLicenseSourceWriteRequest))]
[JsonSerializable(typeof(SoftwareViolationEntry))]
[JsonSerializable(typeof(IReadOnlyList<DeviceSummary>))]
[JsonSerializable(typeof(IReadOnlyList<InstalledSoftwareEntry>))]
[JsonSerializable(typeof(IReadOnlyList<SoftwareAggregate>))]
[JsonSerializable(typeof(IReadOnlyList<SoftwareDevice>))]
[JsonSerializable(typeof(IReadOnlyList<SoftwarePolicyEntry>))]
[JsonSerializable(typeof(IReadOnlyList<SoftwareViolationEntry>))]
[JsonSerializable(typeof(WebhookPayload))]
[JsonSerializable(typeof(NewBlacklistViolation))]
[JsonSerializable(typeof(IReadOnlyList<NewBlacklistViolation>))]
public sealed partial class ApiJsonSerializerContext : JsonSerializerContext;
